[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 3
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
